### ISSUE TITLE
Support for Nuvo P-Series Players

### ISSUE THREAD

**Issue by ChrisColotti** [Willmac16/homebridge-nuvo#12]
It does not appear this supports this line of players, but can you confirm?  I have a stack of P4300's

**Comment by Willmac16** [comment]
Yeah, this plug-in works with the rs232 connection on grand concerto receivers, and it looks like the p4300s don't have rs232 or don't have a public control scheme.

**Comment by Willmac16** [comment]
That sounds like a big positive step from the Grand Concerto and Music Port era.

Maybe if I had a p4300 of my own and, more importantly, more time I'd take that on, but for now I'm focused on school.
