### ISSUE TITLE
Initial volume not always being set correctly

### ISSUE THREAD

**Issue by kiwi64ajs** [Willmac16/homebridge-nuvo#16]
Hmmm... I've been having some issues with the initial Zone turn-on as the Zone can end up showing 70% (my setting) on the Home app icon but the zone is still silent (or maybe very quiet as its in the next room to my desk).
There must be a race condition here as what I've ended up doing for now is to use NodeRed to send a { "Brightness": 69 } and then half a second later send { "Brightness": 70 } and it seems to work more reliably although its not gotten much of a workout yet.

On the "Homebridge Settings" page I can see a "Homebridge Debug Mode -D" switch to enable logging but is there a way to selectively enable DEBUG for just your plug-in? Perhaps put some magic string into the Environment Variable fields "DEBUG" or "NODE_OPTIONS" fields below the Debug Mode switch.

**Comment by Willmac16** [comment]
As far as I know, the official logging setup for homebridge only has bridge wide debug mode. You may be able to run homebridge in a child bridge or something to focus on the nuvo debug, but I've generally just ignored/disabled other plugins that are filling the log when I need to focus on nuvo.

**Comment by Willmac16** [comment]
@kiwi64ajs version `2.3.0` should fix the power on volume issues. Let me know if you're seeing issues
