### ISSUE TITLE
Serial socket issue

### ISSUE THREAD

**Issue by TMidi84** [Willmac16/homebridge-nuvo#21]
Hi Willmac,  thanks for all the great work that you've done with this pluggin. I recently came across this and wanted to bring my nuvo grand to the modern age. After doing all the setup and everything appearing to be properly operating I am getting this error message:

```
[nuvo-platform] That serial port didn't open right now. I will try again in 60 second(s).
[7/24/2023, 8:08:12 AM] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge A844) is running on port 51266.
Failed to create listener for avahi-daemon server state. The system will not be notified about restarts of avahi-daemon and will therefore stay undiscoverable in those instances. Error message: Error: No such interface found
```

I have searched far  and wide looking for where this could be a setup issue and have been unable to find anything to guide or help me solve. Any way you can take a look at this.

**Comment by Willmac16** [comment]
It looks like the plugin can't open the serial port you've listed in the config.

[ ] Can you send your config
And
[ ] Can you send the result of `dmesg | grep -i usb`
[ ] running homebridge with `sudo` or adding the user to dialout could also solve it
