### ISSUE TITLE
Check COM port availability

### ISSUE THREAD

**Issue by miticolars** [Willmac16/homebridge-nuvo#5]
Thank you for your work and for this useful plugin. I've a request of enhancement for this tool. I keep my nuvo system turned off if i don't want to use it (without power), but if the plugin starts in these conditions (for example if I restart homebridge for other configurations) it loose every source/zone (I think because it try to connect to the COM port only in the startup phase). Is it possible to check for COM port availability with a timer until it works (and to keep the accessories previously configured)? Thank you very much for you help

**Comment by Willmac16** [comment]
I just pushed an update that added this in.

**Comment by miticolars** [comment]
@Willmac16 great! I've just updated the plugin and now I test it on my environment. Thank you!

**Comment by Willmac16** [comment]
Make sure to set the portRetryInterval accordingly.

**Comment by miticolars** [comment]
@Willmac16 I forgot to give you a feedback, i'm sorry. It works! thank you so much.
