### ISSUE TITLE
Config Issue:  Nuvo Concerto 16 Zone

### ISSUE THREAD

**Issue by marsbars-marsbars** [Willmac16/homebridge-nuvo#6]
@Willmac16 

Hi there!  Thank you so much for taking the time to write this plugin for Homebridge!   

I am having an issue where, I receive some log errors, and there are only three accessories showen for the Nuvo audio system.  Where am I going wrong?

[nuvo-platform] Initializing nuvo-platform platform...
Setup Payload:
X-HM://0024JYS4U53K3
[01/12/2020, 13:24:46] [nuvo-platform] Port setup process seems to have worked. Yay!
(node:1321) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 052150bd-10f1-4861-949b-05dc4cfc7dbc
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:416:15)
    at Bridge.Accessory._this.addBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:450:12)
    at Server.handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:528:17)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:316:10)
    at NuvoPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-nuvo/src/platform.ts:182:22)
    at NuvoPlatform.addZone (/usr/local/lib/node_modules/homebridge-nuvo/src/platform.ts:197:26)
    at /usr/local/lib/node_modules/homebridge-nuvo/src/serial.ts:208:31
    at ReadLineParser.<anonymous> (/usr/local/lib/node_modules/homebridge-nuvo/src/serial.ts:189:24)
    at ReadLineParser.emit (events.js:315:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1321) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1321) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[01/12/2020, 13:24:54] [Homebridge UI] Terminal session ended.

**Comment by Willmac16** [comment]
I believe that you can delete the `.homebridge/accessories/cachedAccesories` file to fix this. I think this could have happened if you updated the plugin or if you added zones/

**Comment by Willmac16** [comment]
@marsbars-marsbars Let me if that fixes it. If not, I could hop into a discord chat and help you debug.

**Comment by stuartpreston** [comment]
I had a similar issue and discovered two of my "unused" sources were named identically. If you can use the PC configuration tool to rename all your sources uniquely I think it should work. https://github.com/Willmac16/homebridge-nuvo/issues/4#issuecomment-757492194

**Comment by Willmac16** [comment]
I am writing a command line tool that will come with the plugin and will let you do configuration without the PC configuration tool.

**Comment by 64Spaces** [comment]
> I am writing a command line tool that will come with the plugin and will let you do configuration without the PC configuration tool.

That sounds awesome. The old Windows interface is pretty clunky. Do you have a tip jar somewhere?

**Comment by Willmac16** [comment]
@64Spaces my paypal should show up in the donate section of the UI. Thanks!

**Comment by 64Spaces** [comment]
> 
> 
> @64Spaces my paypal should show up in the donate section of the UI. Thanks!

Thanks, but I've been looking around github and could not find anything.

**Comment by Willmac16** [comment]
@64Spaces I just added a donation section to GitHub (I had added it to the plugin's homebridge config ui section earlier).

**Comment by 64Spaces** [comment]
> @64Spaces I just added a donation section to GitHub (I had added it to the plugin's homebridge config ui section earlier).

Perfect, thank you! My Homebridge is running headless, so this is much easier. Donation sent. I’ll explore the upgrade this weekend.

**Comment by marsbars-marsbars** [comment]
@Willmac16  First off, thank you for developing this homebridge plugin.  Apologies for the delay, with holidays and such I had to table this project.   I have since rebuilt my hombridge pi, installed your latest plugin and I see all the accessories (I believe). 

Can you confirm what I should see in the homebridge accessories for Nuvo?   What I am seeing is what appears to be on / off items for my six sources by zone.  Is that correct?    Can I control volume ?

**Comment by Willmac16** [comment]
@marsbars-marsbars yes you should see an accessory for each zone source pair. You should be able to set the volume with the brightness slider (this plugin displays the accessories as lights so you can control them with Siri).
