### ISSUE TITLE
Generate a unique serial number for each accessory created?

### ISSUE THREAD

**Issue by brownmann14** [Willmac16/homebridge-nuvo#9]
Hello

First off thank you for your hard work on this. This integration allows me to integrate my 6 zone nuvo into homebridge perfectly. 

The issue im having is with home assistant(HA)
Background:  Using HA i can add "homekit ready" bridges/devices and even an entire homebridge instance for control through HA. The reason I do this is that HA itself does not have an integration with nuvo through serial port. I placed the nuvo-platform on a child bridge and added it succesfully to HA. The issue is that not all my accesories appear in HA. Only one appears and the rest are ignored. The one source/zone accesory that does appear works perfectly (on/off and volume control)

After some googling I found this: 
Thread: https://github.com/home-assistant/core/issues/34121
Comment: https://github.com/home-assistant/core/issues/34121#issuecomment-735719110

From what i understand the other source/zone accessories are ignored due to not having a unique serial number which is required by HA for a proper connection. I see the errors in my HA log but i wont bother you with that :)

I know that there may not be many people in my specific use case scenario. But your plugin works very well so id like to leverage it. So i was wondering is it possible to generate the serial numbers in this plugin?

**Comment by Willmac16** [comment]
@brownmann14 It should be quite doable. I (and every homebridge plugin) am generating a unique identifier (uuid) for each accessory. I can rather quickly set the serial number to match that unique identifier, but I will also take a look at home-assistant and make a pr if necessary since it seems to me like they should be using the uuid from accessories rather than the serial number.

**Comment by brownmann14** [comment]
I believe that if you allowed the uuid and serial numbers to match it may get my use case working. I'm more than happy to try it out if you make the change. 
But I will allow you to take your time and look into the inner workings of HA. 

Again, thank you so much for your efforts

**Comment by Willmac16** [comment]
I released 2.2.3, which has the fix. I'll probably take a look at running a home-assistant instance (I'm already running two homebridge instances, so it shouldn't be too much more). I'm glad that you enjoy the plugin!
